baseURL = 'https://niuzj.org/'
languageCode = 'zh-cn'
title = 'niuzj'
theme = 'PaperMod'

[params]
  env = "production"
  description = "niuzj 的技术博客"
  author = "niuzj"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "Hey 👋"
    Content = "欢迎来到我的技术博客"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/day0n"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
