baseURL = 'https://niuzj.org/'
languageCode = 'zh-cn'
title = 'niuzj'
theme = 'paper'
paginate = 5

[params]
  color = 'linen'
  avatar = '/favicon-192x192.png'
  name = 'niuzj'
  bio = '技术博客'
  github = 'day0n'
  twitter = 'hohohteniu'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "mailto:niuzj0@gmail.com"
    weight = 20
